version: '3.5'
services:
  redis:
    image: 'redis:latest'
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - proxynet
  api:
    links:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./calculation-api
    expose:
      - "8080"
    networks:
      - proxynet
    environment:
      - REDIS_HOST=redis
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - proxynet
networks:
  proxynet:
    name: calculation_network